#!/usr/bin/env python
# coding: utf-8

# In[1]:


import streamlit as st
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
import numpy as np


# In[2]:


# Load the saved BERT model
model = tf.keras.models.load_model("model-bert.h5", custom_objects={'KerasLayer': hub.KerasLayer})

# Streamlit App
st.title("AI-Generated vs Human-Generated Text Classifier")
st.write("Enter a piece of text below, and the model will predict whether it is AI-generated or human-generated.")

# Text input from user
text_input = st.text_area("Enter your text here:", height=200)

# Threshold for classification
threshold = 0.3  # As you used in main.py

# Prediction Function
def predict(text):
    # Convert the input text to tensor
    text_tensor = tf.convert_to_tensor([text])
    
    # Predict the probability
    prediction = model.predict(text_tensor)[0][0]
    
    # Apply threshold
    if prediction >= threshold:
        return "AI-Generated", prediction
    else:
        return "Human-Generated", prediction

# Predict button
if st.button("Predict"):
    if text_input.strip() == "":
        st.warning("Please enter some text.")
    else:
        label, confidence = predict(text_input)
        
        # Display result
        st.success(f"**Prediction:** {label}")
        st.info(f"**Confidence Score:** {confidence:.2f}")
        
        # Add some conditional text
        if label == "AI-Generated":
            st.write("The model predicts that this text was generated by an AI.")
        else:
            st.write("The model predicts that this text was written by a human.")

# Footer
st.markdown("---")
st.write("Built with BERT and Streamlit")


# In[ ]:




